{
 "title": "PRINCIPAL / MANAGEMENT DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dept",
    "label": "Department",
    "query": "SELECT DISTINCT \"department_name\" FROM \"hari\";"
   },
   {
    "name": "year",
    "label": "Academic Year",
    "query": "SELECT DISTINCT \"academic_year\" FROM \"hari\";"
   },
   {
    "name": "college",
    "label": "College",
    "query": "SELECT DISTINCT \"college_name\" FROM \"hari\" ORDER BY 1;"
   },
   {
    "name": "student",
    "label": "Student",
    "query": "SELECT DISTINCT \"student_name\" FROM \"hari\" WHERE \"college_name\" IN ($college) AND \"department_name\" IN ($dept) ORDER BY 1;"
   },
   {
    "name": "mentor",
    "label": "Mentor",
    "query": "SELECT DISTINCT \"mentor_name\" FROM \"hari\" WHERE \"college_name\" IN ($college) AND \"department_name\" IN ($dept) ORDER BY 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Participation Reach",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \r\n  SUM(CAST(\"total_participants\" AS NUMERIC)) AS \"Total Participation Reach\"\r\nFROM \"hari\"\r\nWHERE \"college_name\" IN ($college)\r\n  AND \"academic_year\" IN ($year)\r\n  AND \"department_name\" IN ($dept);"
    }
   ]
  },
  {
   "title": "Average Package (LPA)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyINR" } },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  ROUND(AVG(CAST(\"avg_package_lpa\" AS NUMERIC)), 2) AS \"Avg Package (LPA)\"\nFROM \"hari\"\nWHERE \"college_name\" IN ($college)\n  AND \"department_name\" IN ($dept)\n  AND \"academic_year\" IN ($year)\n  AND \"mentor_name\" IN ($mentor)\n  AND \"student_name\" IN ($student);"
    }
   ]
  },
  {
   "title": "Hackathon Project Completion Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  (SUM(CAST(\"projects_completed\" AS NUMERIC)) * 100.0 / \n   NULLIF(SUM(CAST(\"projects_submitted\" AS NUMERIC)), 0)) AS \"Success Rate\"\nFROM \"hari\"\nWHERE \"college_name\" IN ($college)\n  AND \"department_name\" IN ($dept)\n  AND \"academic_year\" IN ($year)\n  AND \"mentor_name\" IN ($mentor)\n  AND \"student_name\" IN ($student);"
    }
   ]
  },
  {
   "title": "Lab & Software Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \r\n  AVG(CAST(\"lab_utilization_pct\" AS NUMERIC)) AS \"Lab Utilization (%)\"\r\nFROM \"hari\"\r\nWHERE \"college_name\" IN ($college)\r\n  AND \"department_name\" IN ($dept)\r\n  AND \"academic_year\" IN ($year)\r\n  AND \"mentor_name\" IN ($mentor)\r\n  AND \"student_name\" IN ($student);"
    }
   ]
  },
  {
   "title": "Top 10 Student Performers",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  student_name AS \"Student\",\n  AVG(problem_solving_score_avg::numeric) AS \"Performance Score\"\nFROM hari\nWHERE college_name IN ($college)\n  AND academic_year IN ($year)\nGROUP BY student_name\nORDER BY \"Performance Score\" DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Gender Participation Ratio",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  'Female Students' AS metric, \n  AVG(CAST(\"female_participation_pct\" AS NUMERIC)) AS percentage\nFROM \"hari\"\nWHERE \"college_name\" IN ($college)\n  AND \"department_name\" IN ($dept)\n  AND \"academic_year\" IN ($year)\n  AND \"mentor_name\" IN ($mentor)\n  AND \"student_name\" IN ($student)\n\nUNION ALL\n\nSELECT \n  'Male Students' AS metric, \n  (100 - AVG(CAST(\"female_participation_pct\" AS NUMERIC))) AS percentage\nFROM \"hari\"\nWHERE \"college_name\" IN ($college)\n  AND \"department_name\" IN ($dept)\n  AND \"academic_year\" IN ($year)\n  AND \"mentor_name\" IN ($mentor)\n  AND \"student_name\" IN ($student);"
    }
   ]
  },
  {
   "title": "Top-10 Performing Departments",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  department_name AS \"Department\",\n  AVG(NULLIF(problem_solving_score_avg, '')::numeric) AS \"Avg Performance Score\"\nFROM hari\nWHERE college_name IN ($college)\n  AND academic_year IN ($year)\nGROUP BY department_name\nORDER BY \"Avg Performance Score\" DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Student Performance Segmentation by Skill Level",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  student_name AS \"Student\",\n  department_name AS \"Department\",\n  mentor_name AS \"Mentor\",\n  ROUND(NULLIF(problem_solving_score_avg, '')::numeric, 2) AS \"Tech Score\",\n  CASE \n    WHEN NULLIF(problem_solving_score_avg, '')::numeric >= 80 THEN 'Elite (80+)'\n    WHEN NULLIF(problem_solving_score_avg, '')::numeric >= 65 THEN 'Pro (65–79)'\n    WHEN NULLIF(problem_solving_score_avg, '')::numeric >= 50 THEN 'Intermediate (50–64)'\n    ELSE 'Beginner (<50)'\n  END AS \"Performance Category\"\nFROM hari\nWHERE college_name IN ($college)\n  AND department_name IN ($dept)\n  AND academic_year IN ($year)\n  AND student_name IN ($student)\n  AND mentor_name IN ($mentor)\nORDER BY \n  \"Performance Category\",\n  \"Tech Score\" DESC;\n"
    }
   ]
  },
  {
   "title": "Faculty Mentorship by Department",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  mentor_name AS \"Mentor\",\n  ROUND(AVG(NULLIF(problem_solving_score_avg, '')::numeric), 2) AS \"Mentor Impact Score\"\nFROM hari\nWHERE college_name IN ($college)\n  AND department_name IN ($dept)\n  AND academic_year IN ($year)\n  AND mentor_name IN ($mentor)\nGROUP BY mentor_name\nORDER BY \"Mentor Impact Score\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "Hackathon Impact on Student Academic Readiness",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 27 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  CASE\n    WHEN NULLIF(problem_solving_score_avg, '')::numeric >= 75 \n      THEN 'Ready for Advanced Opportunities'\n    WHEN NULLIF(problem_solving_score_avg, '')::numeric BETWEEN 55 AND 74 \n      THEN 'Moderately Prepared'\n    ELSE 'Needs Further Training'\n  END AS \"Readiness Level\",\n  COUNT(DISTINCT student_name) AS \"Number of Students\"\nFROM hari\nWHERE college_name IN ($college)\n  AND department_name IN ($dept)\n  AND academic_year IN ($year)\n  AND student_name IN ($student)\n  AND mentor_name IN ($mentor)\nGROUP BY \n  CASE\n    WHEN NULLIF(problem_solving_score_avg, '')::numeric >= 75 \n      THEN 'Ready for Advanced Opportunities'\n    WHEN NULLIF(problem_solving_score_avg, '')::numeric BETWEEN 55 AND 74 \n      THEN 'Moderately Prepared'\n    ELSE 'Needs Further Training'\n  END\nORDER BY \"Number of Students\" DESC;\n"
    }
   ]
  },
  {
   "title": "Top-3 Colleges",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  college_name AS \"College\",\n  ROUND(AVG(NULLIF(problem_solving_score_avg, '')::numeric), 2) AS \"Avg Tech Score\",\n  COUNT(DISTINCT student_name) AS \"Participants\"\nFROM hari\nGROUP BY college_name\nORDER BY \"Avg Tech Score\" DESC\nLIMIT 3;\n"
    }
   ]
  },
  {
   "title": "Hackathon",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "grafana-hackathon",
     "rawSql": "SELECT \n  academic_year AS \"Year\",\n  department_name AS \"Department\",\n  mode AS \"Mode\",\n  NULLIF(total_participants, '')::numeric AS \"Students\",\n  NULLIF(prizes_won_count, '')::numeric AS \"Prizes\",\n  ROUND(NULLIF(problem_solving_score_avg, '')::numeric, 2) AS \"Tech Score\",\n  NULLIF(students_placed, '')::numeric AS \"Placed\",\n  ROUND(NULLIF(highest_package_lpa, '')::numeric, 2) AS \"Max Package (LPA)\",\n  ROUND(NULLIF(budget_utilized, '')::numeric, 2) AS \"Budget (₹)\",\n  software_tools_used AS \"Tools Used\"\nFROM hari\nWHERE college_name IN ($college)\n  AND department_name IN ($dept)\n  AND academic_year IN ($year)\n  AND student_name IN ($student)\n  AND mentor_name IN ($mentor)\nORDER BY academic_year DESC, prizes_won_count DESC;\n"
    }
   ]
  }
 ]
}